
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Final_Capstone_rails_backend_development

test:
  <<: *default
  database: Final_Capstone_rails_backend_test


production:
  <<: *default
  database: Final_Capstone_rails_backend_production
  username: Final_Capstone_rails_backend
  password: <%= ENV["FINAL_CAPSTONE_RAILS_BACKEND_DATABASE_PASSWORD"] %>
